### ISSUE TITLE
Consider pushing images with --squash

### ISSUE THREAD

**Issue by stewartadam** [smart-on-fhir/hapi#1]
Current [docker image](https://hub.docker.com/r/smartonfhir/hapi/) has a redundant ~250MB layer due to the downloading, then unpacking, of a large tar.bz2 file which is removed later in the build.

`docker build --squash` will diff layers produced in your build and squash them to a single image - [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) could also help eliminate the redundant layer.

**Comment by vlad-ignatov** [comment]
Thank you for pointing this out. The images were squashed and re-deployed to https://hub.docker.com/r/smartonfhir/hapi/tags/.
